export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
